// Barrel — re-exports from split modules in ./models/
export {
  type Provider,
  type ModelDef,
  MODEL_REGISTRY,
  MODELS,
  EMBEDDING_DIMENSION,
  getSupportedModels,
  isFixedTempModel,
  isReasoningModel,
  isNanoModel,
  isEmbeddingModel,
  getModelPricing,
  getModelProvider,
  AGENT_SELECTABLE_MODELS,
  TIER_MULTIPLIER,
  findSelectableModel,
  parseCompositeId,
  type SelectableModel,
  type ModelTier,
} from "./models/index.js";
